### PR TITLE
Autowired filters

### PR DESCRIPTION
**Pull request by MartinSzollos2016**
Is it necessary set filters autowiring false?
Format settings are set in config.neon.
Am i missing something ?

### CODE REVIEW

**Comment by MartinSzollos2016** [comment]
This lines throws:
Too few arguments to function h4kuna\Exchange\DI\ExchangeExtension::__construct()

	public function __construct(string $tempDir)
	{
		$this->defaults['tempDir'] = $tempDir . DIRECTORY_SEPARATOR . 'currencies';
	}

**Comment by h4kuna** [comment]
ad Autowire) ths option you can enable in your neon
```
extensions:
	exchange: h4kuna\Exchange\DI\ExchangeExtension

services:
	exchange.filters:
		autowired: on
```

**Comment by h4kuna** [comment]
Set tempDir like this
```
extensions:
	exchange: h4kuna\Exchange\DI\ExchangeExtension(%tempDir%)
```
API for DI in Nette is changed for this moment i wait for stable release. How comfortably set tempDir.

**Comment by h4kuna** [comment]
Is Autowire heplful?

**Comment by h4kuna** [comment]
in this moment i do not merge it, i must think about these changes.

**Comment by MartinSzollos2016** [comment]
> Is Autowire heplful?

For me yes. I pass filters instead of exchange in component constructor.
I dont have to do exchange->change and then filters->format.
Older version of exchange had format function.

**Comment by h4kuna** [comment]
I don't see trouble. If you enable autowire than is alright. Here is [format function](/h4kuna/exchange/blob/master/src/Filters.php#L48). If you want add more filter to latte, you can do it in neon.
```
latte.latteFactory: # or nette.latteFactory:
	setup:
		- addFilter('formatTo', [@exchange.filters, formatTo])
```

**Comment by MartinSzollos2016** [comment]
I also do not see any problem. I thought it might be helpful for other people, but i forgot that you can set autowiring in config.

**Comment by h4kuna** [comment]
Added more filters

**Pull request closed without merging**
